#!/bin/bash
echo "Testing BAD input"
LINUX badInput1 2>f ;  grep -v "seed line format error" f
LINUX badInput2 2>f ;  grep -v "seed line format error" f
LINUX badInput3 2>f ; grep -v "card format error" f
LINUX badInput4 2>f ; grep -v "card format error" f
LINUX badInput5 2>f ; grep -v "card format error" f
LINUX badInput6 2>f ; grep -v "card format error" f
LINUX badInput7 2>f ; grep -v "card format error" f
LINUX badInput8 2>f ; grep -v "card format error" f
LINUX badInput9 2>f ; grep -v "card format error" f
rm f 2>/dev/null
for i in $(seq 0 3) ; do
  echo "hit any key to test goodInput${i}"
  read -r k
  echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
    | LINUX goodInput${i}
done
